name: invoice
description: Conversion of invoice desktop app to mobile
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2023.01.15

environment:
  sdk: ">=2.17.6 <4.9.9"

dependencies:
  get: 4.6.5
  get_cli: ^1.6.0
  get_storage: ^2.0.3
  cupertino_icons: ^1.0.2
  connectivity_plus: ^5.0.1
  json_annotation: ^4.5.0
  provider: ^6.0.1
  email_validator: ^2.0.1
  iconsax: ^0.0.8
  http: ^1.1.0
  shared_preferences: ^2.0.6
  curved_navigation_bar: ^1.0.3
  another_flushbar: ^1.10.28
  flutter_calendar_widget: ^0.0.2
  table_calendar: ^3.0.8
  animation_list: ^2.2.1
  mongo_dart: ^0.10.0
  excel: ^3.0.0
  uuid: ^4.3.3
  intl: ^0.17.0
  pdf: ^3.10.1
  permission_handler: ^11.0.1
  mailer: ^6.0.1
  flutter_dotenv: ^5.1.0
  page_view_dot_indicator: ^2.0.0
  flutter_email_sender: ^6.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  download: ^1.0.0
  path_provider: ^2.0.14
  flutter_secure_storage: ^8.0.0
  document_file_save_plus: ^2.0.0
  file_manager: ^1.0.2
  share_plus: ^5.0.0
  image_picker: ^1.0.4
  pdf_viewer_plugin: ^2.0.1
  firebase_messaging: ^14.6.2
  rxdart: ^0.27.7
  flutter_local_notifications: ^16.1.0
  url_launcher: ^6.1.11
  maps_launcher: ^2.2.0
  uni_links: 0.5.1
  pinput: ^3.0.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  crypto: ^3.0.1
  flutter:
    sdk: flutter
  argon2: ^1.0.1
  lottie: ^2.7.0
  media_store_plus: ^0.0.7
  firebase_storage: ^11.6.0
  firebase_app_check: ^0.2.1+8
  image_cropper: ^5.0.1
  auto_size_text: ^3.0.0
  speech_to_text: ^6.5.1


dev_dependencies:
  flutter_lints: ^3.0.1
  lints: ^3.0.0
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
    - assets/images/client-profile.png
    - assets/images/placeholder_product.png
    - assets/images/she_with_phone.png
    - assets/images/he_sitting_with_notebook.png
    - assets/images/invoice_banner.png
    - assets/images/Invo.gif
    - assets/images/splash_gif.gif
    - assets/images/ud.gif
    - assets/images/splash_screen.png
    - assets/images/splash_screen.gif
    - assets/icons/fav-folder-dynamic-color.png
    - assets/icons/fav-folder-dynamic-premium.png
    - assets/icons/profile_placeholder.png
    - lib/main.dart
    - assets/lottieAnimationJSON/loading_horizontal_line.json
    - assets/lottieAnimationJSON/warning.json
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"






